version: '3.3'

services:
  nginx:
    image: nginx:stable-alpine
    ports:
      - 8007:80
    volumes:
      - '$PWD/nginx.conf:/etc/nginx/conf.d/default.conf'
      - '$PWD/dist:/usr/share/nginx/html'
